[package]
name = "winio"
version = "0.1.0"
edition = "2021"

[dependencies]
compio = { version = "0.9.0-beta.4", features = ["nightly", "native-tls"] }
compio-log = "0.1.0-beta.1"
euclid = "0.22"
futures-util = "0.3"
once_cell = "1"
rgb = "0.8"
slab = "0.4"
widestring = "1"
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
] }
windows = { version = "0.53", features = [
    "Foundation_Numerics",
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
] }

[dev-dependencies]
compio = { version = "0.9.0-beta.4", features = ["time"] }
cyper = { version = "0.1.0-beta.1", features = ["nightly"] }
tracing-subscriber = "0.3"

[build-dependencies]
embed-resource = "2"

[features]
default = []
enable_log = ["compio/enable_log", "compio-log/enable_log"]

once_cell_try = ["compio/once_cell_try"]
lazy_cell = ["compio/lazy_cell"]
nightly = ["compio/nightly", "cyper/nightly", "once_cell_try", "lazy_cell"]

[patch.'crates-io']
compio = { git = "https://github.com/Berrysoft/compio.git", branch = "dev/runtime-hook" }
compio-log = { git = "https://github.com/Berrysoft/compio.git", branch = "dev/runtime-hook" }
cyper = { git = "https://github.com/Berrysoft/cyper.git", branch = "update-hyper-with-util" }
