[package]
name = "winio"
version = "0.1.8"
edition = "2021"
description = "Single-threaded async GUI runtime based on compio."
license = "MIT"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
readme = "README.md"
repository = "https://github.com/compio-rs/winio"
categories = ["asynchronous", "gui"]
keywords = ["async", "gui"]

[dependencies]
compio = "0.12.0"
compio-log = "0.1.0"

cfg-if = "1"
euclid = "0.22"
futures-util = { version = "0.3", features = ["alloc"] }
futures-channel = "0.3"
once_cell = "1"
rgb = "0.8"
slab = "0.4"
scoped-tls = "1.0"

[target.'cfg(windows)'.dependencies]
widestring = "1"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Accessibility",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
] }
windows = { version = "0.58", features = [
    "Foundation_Numerics",
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10"
core-graphics = "0.24"
foreign-types-shared = "0.3"

block2 = "0.5"
objc2 = "0.5"
objc2-foundation = { version = "0.2", features = [
    "NSAffineTransform",
    "NSAttributedString",
    "NSDate",
    "NSDictionary",
    "NSEnumerator",
    "NSNotification",
    "NSObjCRuntime",
    "NSRunLoop",
    "NSString",
    "NSThread",
    "NSURL",
    "NSUserDefaults",
] }
objc2-app-kit = { version = "0.2", features = [
    "block2",
    "NSAlert",
    "NSApplication",
    "NSAttributedString",
    "NSBezierPath",
    "NSButton",
    "NSButtonCell",
    "NSColor",
    "NSControl",
    "NSEvent",
    "NSFont",
    "NSFontDescriptor",
    "NSGraphics",
    "NSGraphicsContext",
    "NSOpenPanel",
    "NSPanel",
    "NSResponder",
    "NSRunningApplication",
    "NSSavePanel",
    "NSScreen",
    "NSStringDrawing",
    "NSTextField",
    "NSTrackingArea",
    "NSView",
    "NSWindow",
    "NSWindowScripting",
] }
objc2-uniform-type-identifiers = { version = "0.2", features = ["UTType"] }

[target.'cfg(not(any(windows, target_os = "macos")))'.dependencies]
gtk4 = { version = "0.9", optional = true, features = ["v4_14"] }
pangocairo = { version = "0.20", optional = true }

cxx = { version = "1.0", optional = true, features = ["c++20"] }

[dev-dependencies]
compio = { version = "0.12.0", features = ["time", "native-tls"] }
cyper = { version = "0.1.5", default-features = false, features = [
    "rustls",
    "http2",
    "http3-altsvc",
] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }

futures-util = "0.3"
tracing-subscriber = "0.3"

[build-dependencies]
embed-resource = "2"

cxx-build = { version = "1.0", optional = true }
qt-build-utils = { version = "0.6", optional = true }

[features]
default = ["qt"]
gtk = ["dep:gtk4", "dep:pangocairo"]
qt = ["dep:cxx", "dep:cxx-build", "dep:qt-build-utils"]
enable_log = ["compio/enable_log", "compio-log/enable_log"]

nightly = ["compio/nightly", "cyper/nightly"]

[profile.release]
lto = true
codegen-units = 1
