[package]
name = "winio"
version = "0.1.0"
edition = "2021"

[dependencies]
async-task = "4"
compio-log = "0.1.0-beta.1"
crossbeam-queue = "0.3"
euclid = "0.22"
futures-util = "0.3"
slab = "0.4"
widestring = "1.0.2"
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
] }
windows = { version = "0.48", features = [
    "Foundation_Numerics",
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi_Common",
] }
rgb = "0.8"

[dev-dependencies]
tracing-subscriber = "0.3"

[build-dependencies]
embed-resource = "2"

[features]
default = []
enable_log = ["compio-log/enable_log"]
