[package]
name = "winio"
version = "0.1.0"
edition = "2021"

[dependencies]
compio = "0.11.0"
compio-log = "0.1.0"

cfg-if = "1"
euclid = "0.22"
once_cell = "1"
rgb = "0.8"
slab = "0.4"

[target.'cfg(windows)'.dependencies]
widestring = "1"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
] }
windows = { version = "0.58", features = [
    "Foundation_Numerics",
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10"
core-graphics = "0.24"
foreign-types-shared = "0.3"
futures-channel = "0.3"
icrate = { version = "0.1", features = [
    "AppKit",
    "AppKit_NSAlert",
    "AppKit_NSApplication",
    "AppKit_NSBezierPath",
    "AppKit_NSButton",
    "AppKit_NSColor",
    "AppKit_NSEvent",
    "AppKit_NSFont",
    "AppKit_NSFontDescriptor",
    "AppKit_NSGraphicsContext",
    "AppKit_NSOpenPanel",
    "AppKit_NSSavePanel",
    "AppKit_NSScreen",
    "AppKit_NSTextField",
    "AppKit_NSView",
    "AppKit_NSWindow",
    "Foundation",
    "Foundation_NSAffineTransform",
    "Foundation_NSAttributedString",
    "Foundation_NSDate",
    "Foundation_NSDictionary",
    "Foundation_NSNotification",
    "Foundation_NSString",
    "Foundation_NSThread",
    "Foundation_NSURL",
] }

[target.'cfg(not(any(windows, target_os = "macos")))'.dependencies]
gtk4 = { version = "0.9", features = ["v4_10"] }
pangocairo = "0.20"
futures-channel = "0.3"

[dev-dependencies]
compio = { version = "0.11.0", features = ["nightly", "time", "native-tls"] }
cyper = { version = "0.1.0-beta.4", features = ["nightly"] }

futures-util = "0.3"
tracing-subscriber = "0.3"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "2"

[features]
default = []
enable_log = ["compio/enable_log", "compio-log/enable_log"]

once_cell_try = ["compio/once_cell_try"]
lazy_cell = ["compio/lazy_cell"]
nightly = ["compio/nightly", "cyper/nightly", "once_cell_try", "lazy_cell"]
