[package]
name = "winio"
version = "0.1.0"
edition = "2021"

[dependencies]
async-task = "4"
compio-buf = { version = "0.2.0-beta.1", features = ["nightly"] }
compio-io = { version = "0.1.0-beta.2", features = ["nightly"] }
compio-log = "0.1.0-beta.1"
crossbeam-queue = "0.3"
euclid = "0.22"
futures-util = "0.3"
slab = "0.4"
widestring = "1.0.2"
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
] }
windows = { version = "0.48", features = [
    "Foundation_Numerics",
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi_Common",
] }
rgb = "0.8"

[dev-dependencies]
tracing-subscriber = "0.3"

[build-dependencies]
embed-resource = "2"

[features]
default = []
enable_log = ["compio-log/enable_log"]
