[workspace]
members = ["winio", "winio-primitive", "winio-layout"]

resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/compio-rs/winio"

[workspace.dependencies]
winio-primitive = { path = "winio-primitive", version = "0.1.0" }
winio-layout = { path = "winio-layout", version = "0.1.0" }

paste = "1.0"

[profile.release]
lto = true
codegen-units = 1
