[package]
name = "winio"
version = "0.1.0"
edition = "2021"

[dependencies]
async-task = "4"
compio = { version = "0.9.0-beta.4", features = ["nightly", "native-tls"] }
compio-log = "0.1.0-beta.1"
crossbeam-queue = "0.3"
either = "1"
euclid = "0.22"
futures-util = "0.3"
http-body-util = "0.1"
hyper = "1"
hyper-util = { version = "0.1", features = ["client-legacy", "http1"] }
pin-project = "1"
rgb = "0.8"
send_wrapper = { version = "0.6", features = ["futures"] }
slab = "0.4"
socket2 = { version = "0.5", features = ["all"] }
tower-service = "0.3"
widestring = "1"
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
] }
windows = { version = "0.53", features = [
    "Foundation_Numerics",
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
] }

[dev-dependencies]
compio = { version = "0.9.0-beta.4", features = ["time"] }
cyper-core = { version = "0.1.0-beta.1", features = ["client"] }
tracing-subscriber = "0.3"

[build-dependencies]
embed-resource = "2"

[features]
default = []
enable_log = ["compio/enable_log", "compio-log/enable_log"]

[patch.'crates-io']
compio = { git = "https://github.com/Berrysoft/compio.git", branch = "dev/runtime-hook" }
compio-log = { git = "https://github.com/Berrysoft/compio.git", branch = "dev/runtime-hook" }
cyper-core = { git = "https://github.com/Berrysoft/cyper.git", branch = "update-hyper-with-util" }
