[package]
name = "winio-elm"
version = "0.1.0"
description = "ELM framework for winio."
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
winio-primitive = { workspace = true }
winio-layout = { workspace = true }
winio-handle = { workspace = true }

futures-util = { workspace = true, features = ["alloc"] }
inherit-methods-macro = { workspace = true }
paste = { workspace = true }
smallvec = "1"
