[package]
name = "winio"
version = "0.7.0-beta.2"
description = "Single-threaded async GUI runtime based on compio."
categories = ["asynchronous", "gui"]
keywords = ["async", "gui"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
winio-primitive = { workspace = true }
winio-layout = { workspace = true }
winio-handle = { workspace = true }
winio-elm = { workspace = true }

compio = { workspace = true }
compio-log = { workspace = true }

cfg-if = { workspace = true }
futures-util = { workspace = true }
image = { workspace = true, default-features = false }
paste = { workspace = true }
scoped-tls = { workspace = true }

[target.'cfg(windows)'.dependencies]
winio-ui-win32 = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
objc2 = { workspace = true }
objc2-core-foundation = { version = "0.3", features = [
    "CFCGTypes",
    "CFFileDescriptor",
    "CFRunLoop",
] }
objc2-core-graphics = { version = "0.3", features = ["CGColor", "CGPath"] }
objc2-foundation = { version = "0.3", features = [
    "NSAffineTransform",
    "NSAttributedString",
    "NSDate",
    "NSDictionary",
    "NSEnumerator",
    "NSNotification",
    "NSObjCRuntime",
    "NSRunLoop",
    "NSString",
    "NSThread",
    "NSURL",
    "NSUserDefaults",
] }
objc2-app-kit = { workspace = true, features = [
    "block2",
    "objc2-core-foundation",
    "objc2-quartz-core",
    "objc2-uniform-type-identifiers",
    "NSAlert",
    "NSApplication",
    "NSAttributedString",
    "NSBitmapImageRep",
    "NSButton",
    "NSButtonCell",
    "NSCell",
    "NSColor",
    "NSColorSpace",
    "NSComboBox",
    "NSControl",
    "NSEvent",
    "NSFont",
    "NSFontDescriptor",
    "NSGraphics",
    "NSImage",
    "NSImageRep",
    "NSMatrix",
    "NSOpenPanel",
    "NSPanel",
    "NSProgressIndicator",
    "NSResponder",
    "NSRunningApplication",
    "NSSavePanel",
    "NSScreen",
    "NSScrollView",
    "NSSecureTextField",
    "NSStringDrawing",
    "NSTableView",
    "NSTableColumn",
    "NSText",
    "NSTextField",
    "NSTrackingArea",
    "NSView",
    "NSWindow",
    "NSWindowScripting",
] }
objc2-uniform-type-identifiers = { version = "0.3", features = ["UTType"] }
objc2-quartz-core = { version = "0.3", features = [
    "objc2-core-graphics",
    "CALayer",
    "CAGradientLayer",
    "CAShapeLayer",
    "CATextLayer",
] }
local-sync = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(not(any(windows, target_os = "macos")))'.dependencies]
winio-ui-gtk = { workspace = true, optional = true }
winio-ui-qt = { workspace = true, optional = true }

[dev-dependencies]
compio = { version = "0.15.0", features = ["time", "rustls", "ring"] }
cyper = { version = "0.4.0", default-features = false, features = [
    "rustls",
    "http2",
    "http3-altsvc",
] }

dirs = "6.0"
futures-util = "0.3"
image = { version = "0.25", default-features = false, features = [
    "default-formats",
] }
itertools = "0.14"
tracing-subscriber = "0.3"

[features]
default = ["qt", "win32-dark-mode"]
gtk = ["dep:winio-ui-gtk"]
qt = ["dep:winio-ui-qt"]
enable_log = ["compio/enable_log", "compio-log/enable_log"]

nightly = ["compio/nightly", "cyper/nightly"]
win32-dark-mode = ["winio-ui-win32/dark-mode"]
objc-static = [
    "objc2/unstable-static-class-inlined",
    "objc2/unstable-static-sel-inlined",
    "objc2-foundation/unstable-static-nsstring",
]
